Repository chill-jo/SURMILE, pull requests merged in 2025-08, with the labels that each got.

#191 refactor: UUID 날짜+ 랜덤값 활용 Issues/189
  src/main/java/com/example/surveyapp/domain/order/model/Order.java
  src/main/java/com/example/surveyapp/domain/product/service/ProductService.java
  src/main/java/com/example/surveyapp/global/response/exception/ErrorCode.java
  src/test/java/com/example/surveyapp/domain/order/controller/OrderControllerTest.java
  src/test/java/com/example/surveyapp/domain/order/service/OrderServiceTest.java
  src/test/java/com/example/surveyapp/domain/product/controller/ProductControllerTest.java
  src/test/java/com/example/surveyapp/domain/product/domain/repository/ProductRepoTest.java
  src/test/java/com/example/surveyapp/domain/product/service/ProductServiceTest.java
Labels: refactor

#192 refactor(#190): 테스트 코드 수정
  src/main/java/com/example/surveyapp/domain/point/controller/PointController.java
  src/main/java/com/example/surveyapp/domain/point/domain/model/entity/Point.java
  src/main/java/com/example/surveyapp/global/response/PageResponse.java
  src/test/java/com/example/surveyapp/config/generator/PointFixtureGenerator.java
  src/test/java/com/example/surveyapp/domain/point/service/PointServiceTest.java
Labels: refactor

#204 test(#203): 테스트 코드 @DisplayName 추가
  src/test/java/com/example/surveyapp/domain/point/service/PointServiceTest.java
Labels: refactor, chore, test

#232 Survey 도메인 DDD 적용 중..
  src/main/java/com/example/surveyapp/domain/admin/domain/model/BlackList.java
  src/main/java/com/example/surveyapp/domain/admin/service/AdminService.java
  src/main/java/com/example/surveyapp/domain/survey/controller/SurveyController.java
  src/main/java/com/example/surveyapp/domain/survey/controller/dto/SurveyMapper.java
  src/main/java/com/example/surveyapp/domain/survey/controller/dto/request/SurveyUpdateRequestDto.java
  src/main/java/com/example/surveyapp/domain/survey/controller/dto/response/OptionResponseDto.java
  src/main/java/com/example/surveyapp/domain/survey/controller/dto/response/SurveyQuestionDto.java
  src/main/java/com/example/surveyapp/domain/survey/controller/dto/response/SurveyeeSurveyDto.java
  src/main/java/com/example/surveyapp/domain/survey/domain/SurveyQuestionQueryService.java
  src/main/java/com/example/surveyapp/domain/survey/domain/SurveyValidator.java
  src/main/java/com/example/surveyapp/domain/survey/domain/model/entity/Options.java
  src/main/java/com/example/surveyapp/domain/survey/domain/model/entity/Question.java
  src/main/java/com/example/surveyapp/domain/survey/domain/model/entity/Survey.java
  src/main/java/com/example/surveyapp/domain/survey/domain/model/entity/SurveyAnswer.java
  src/main/java/com/example/surveyapp/domain/survey/domain/model/entity/SurveyInfo.java
  src/main/java/com/example/surveyapp/domain/survey/domain/repository/OptionsRepository.java
  src/main/java/com/example/surveyapp/domain/survey/domain/repository/SurveyAnswerRepository.java
  src/main/java/com/example/surveyapp/domain/survey/domain/repository/SurveyRepository.java
  src/main/java/com/example/surveyapp/domain/survey/domain/strategy/MultiChoiceAnswerStrategy.java
  src/main/java/com/example/surveyapp/domain/survey/domain/strategy/SingleChoiceAnswerStrategy.java
  src/main/java/com/example/surveyapp/domain/survey/domain/strategy/SubjectAnswerStrategy.java
  src/main/java/com/example/surveyapp/domain/survey/domain/strategy/SurveyQuestionStrategy.java
  src/main/java/com/example/surveyapp/domain/survey/event/SurveyAnswerEvent.java
  src/main/java/com/example/surveyapp/domain/survey/event/SurveyCreateEvent.java
  src/main/java/com/example/surveyapp/domain/survey/service/OptionsService.java
  src/main/java/com/example/surveyapp/domain/survey/service/QuestionService.java
  src/main/java/com/example/surveyapp/domain/survey/service/SurveyService.java
  src/main/java/com/example/surveyapp/domain/survey/service/mapper/SurveyAnswerMapper.java
  src/main/java/com/example/surveyapp/domain/survey/service/mapper/SurveyMapper.java
  src/main/java/com/example/surveyapp/domain/survey/service/strategy/SurveyQuestionStrategy.java
  src/main/java/com/example/surveyapp/domain/user/domain/model/User.java
  src/main/java/com/example/surveyapp/domain/user/domain/repository/UserRepository.java
  src/main/java/com/example/surveyapp/domain/user/infrastructure/UserReaderImpl.java
  src/main/java/com/example/surveyapp/global/reader/UserReader.java
  src/main/java/com/example/surveyapp/global/response/exception/ErrorCode.java
  src/test/java/com/example/surveyapp/config/generator/QuestionFixtureGenerator.java
  src/test/java/com/example/surveyapp/domain/survey/service/OptionsServiceTest.java
  src/test/java/com/example/surveyapp/domain/survey/service/QuestionServiceTest.java
  src/test/java/com/example/surveyapp/domain/survey/service/SurveyServiceTest.java
Labels: refactor

#277 Issues/276 Survey 리팩토링
  src/main/java/com/example/surveyapp/domain/survey/application/OptionsService.java
  src/main/java/com/example/surveyapp/domain/survey/application/QuestionService.java
  src/main/java/com/example/surveyapp/domain/survey/application/SurveyQueryService.java
  src/main/java/com/example/surveyapp/domain/survey/application/SurveyService.java
  src/main/java/com/example/surveyapp/domain/survey/application/facade/UserFacade.java
  src/main/java/com/example/surveyapp/domain/survey/application/mapper/SurveyMapper.java
  src/main/java/com/example/surveyapp/domain/survey/domain/SurveyStatusUpdatePolicy.java
  src/main/java/com/example/surveyapp/domain/survey/domain/SurveyValidator.java
  src/main/java/com/example/surveyapp/domain/survey/domain/event/SurveyCreateEvent.java
  src/main/java/com/example/surveyapp/domain/survey/domain/model/entity/Question.java
  src/main/java/com/example/surveyapp/domain/survey/domain/model/entity/Survey.java
  src/main/java/com/example/surveyapp/domain/survey/domain/model/entity/SurveyInfo.java
  src/main/java/com/example/surveyapp/domain/survey/domain/model/enums/SurveyStatus.java
  src/main/java/com/example/surveyapp/domain/survey/domain/model/vo/SurveyPoints.java
  src/main/java/com/example/surveyapp/domain/survey/domain/repository/OptionsRepository.java
  src/main/java/com/example/surveyapp/domain/survey/domain/repository/QuestionRepository.java
  src/main/java/com/example/surveyapp/domain/survey/domain/service/SurveyQuestionService.java
  src/main/java/com/example/surveyapp/domain/survey/facade/SurveyPointFacade.java
  src/main/java/com/example/surveyapp/domain/survey/infrastructure/QuestionReadEntity.java
  src/main/java/com/example/surveyapp/domain/survey/presentation/OptionsController.java
  src/main/java/com/example/surveyapp/domain/survey/presentation/QuestionController.java
  src/main/java/com/example/surveyapp/domain/survey/presentation/SurveyController.java
  src/main/java/com/example/surveyapp/domain/survey/presentation/dto/request/OptionCreateRequestDto.java
  src/main/java/com/example/surveyapp/domain/survey/presentation/dto/request/OptionUpdateRequestDto.java
  src/main/java/com/example/surveyapp/domain/survey/presentation/dto/request/QuestionCreateRequestDto.java
  src/main/java/com/example/surveyapp/domain/survey/presentation/dto/request/QuestionUpdateRequestDto.java
  src/main/java/com/example/surveyapp/domain/survey/presentation/dto/request/SurveyCreateRequestDto.java
  src/main/java/com/example/surveyapp/domain/survey/presentation/dto/request/SurveyStatusUpdateRequestDto.java
  src/main/java/com/example/surveyapp/domain/survey/presentation/dto/request/SurveyUpdateRequestDto.java
  src/main/java/com/example/surveyapp/domain/survey/presentation/dto/response/OptionResponseDto.java
  src/main/java/com/example/surveyapp/domain/survey/presentation/dto/response/PageQuestionResponseDto.java
  src/main/java/com/example/surveyapp/domain/survey/presentation/dto/response/PageSurveyResponseDto.java
  src/main/java/com/example/surveyapp/domain/survey/presentation/dto/response/QuestionOptionsDto.java
  src/main/java/com/example/surveyapp/domain/survey/presentation/dto/response/QuestionResponseDto.java
  src/main/java/com/example/surveyapp/domain/survey/presentation/dto/response/SurveyQuestionDto.java
  src/main/java/com/example/surveyapp/domain/survey/presentation/dto/response/SurveyResponseDto.java
  src/main/java/com/example/surveyapp/domain/survey/presentation/dto/response/SurveyStatusResponseDto.java
  src/test/java/com/example/surveyapp/config/generator/QuestionFixtureGenerator.java
  src/test/java/com/example/surveyapp/config/generator/SurveyFixtureGenerator.java
  src/test/java/com/example/surveyapp/domain/survey/application/OptionsServiceTest.java
  src/test/java/com/example/surveyapp/domain/survey/application/QuestionServiceTest.java
  src/test/java/com/example/surveyapp/domain/survey/application/SurveyServiceTest.java
Labels: feature, refactor, test

#281 Issues/280 Ai, 패키지 리팩토링
  src/main/java/com/example/surveyapp/domain/ai/moderation/application/NicknameModerationService.java
  src/main/java/com/example/surveyapp/domain/ai/moderation/presentation/NicknameModerationController.java
  src/main/java/com/example/surveyapp/domain/ai/moderation/presentation/dto/NicknameModerationRequestDto.java
  src/main/java/com/example/surveyapp/domain/ai/moderation/presentation/dto/NicknameModerationResponseDto.java
  src/main/java/com/example/surveyapp/domain/order/facade/PointFacade.java
  src/main/java/com/example/surveyapp/domain/order/facade/ProductFacade.java
  src/main/java/com/example/surveyapp/global/config/event/Event.java
  src/main/java/com/example/surveyapp/global/config/event/EventsPublisher.java
  src/main/java/com/example/surveyapp/mockExample/ProductControllerTest.java
Labels: refactor

#287 Issues/286 SurveyAnswer 리팩토링
  src/main/java/com/example/surveyapp/domain/surveyanswer/application/SurveyAnswerQueryService.java
  src/main/java/com/example/surveyapp/domain/surveyanswer/application/facade/SurveyFacade.java
  src/main/java/com/example/surveyapp/domain/surveyanswer/domain/event/SurveyDoneEvent.java
Labels: feature

#295 pointWallet 생성 이벤트, pessimisticLock 적용 메서드 추가
  src/main/java/com/example/surveyapp/domain/point/application/PointService.java
  src/main/java/com/example/surveyapp/domain/point/application/event/UserRegisterEventHandler.java
  src/main/java/com/example/surveyapp/domain/point/domain/repository/PointRepository.java
  src/main/java/com/example/surveyapp/domain/survey/application/SurveyFacadeImpl.java
  src/main/java/com/example/surveyapp/domain/survey/presentation/dto/request/OptionCreateRequestDto.java
  src/main/java/com/example/surveyapp/domain/survey/presentation/dto/request/OptionUpdateRequestDto.java
  src/main/java/com/example/surveyapp/domain/survey/presentation/dto/request/QuestionCreateRequestDto.java
  src/main/java/com/example/surveyapp/domain/survey/presentation/dto/request/QuestionUpdateRequestDto.java
  src/main/java/com/example/surveyapp/domain/survey/presentation/dto/request/SurveyCreateRequestDto.java
  src/main/java/com/example/surveyapp/domain/survey/presentation/dto/request/SurveyStatusUpdateRequestDto.java
  src/main/java/com/example/surveyapp/domain/survey/presentation/dto/request/SurveyUpdateRequestDto.java
  src/main/java/com/example/surveyapp/domain/surveyanswer/presentation/dto/request/QuestionAnswerRequestDto.java
  src/main/java/com/example/surveyapp/domain/surveyanswer/presentation/dto/request/SurveyAnswerRequestDto.java
  src/main/java/com/example/surveyapp/domain/user/application/UserService.java
  src/main/java/com/example/surveyapp/domain/user/domain/event/RegisterEvent.java
  src/test/java/com/example/surveyapp/domain/user/application/UserServiceTest.java
Labels: feature, refactor

#296 Order 리펙토링,Product Api 추가 구현 Issues/290
  src/main/java/com/example/surveyapp/domain/order/presentation/OrderController.java
  src/main/java/com/example/surveyapp/domain/point/domain/model/entity/PointWallet.java
  src/main/java/com/example/surveyapp/domain/product/application/ProductService.java
  src/main/java/com/example/surveyapp/domain/product/application/dto/ProductUpdateResponseDto.java
  src/main/java/com/example/surveyapp/domain/product/domain/model/Product.java
  src/main/java/com/example/surveyapp/domain/product/exception/ProductErrorCode.java
  src/main/java/com/example/surveyapp/domain/product/infrastructure/ProductFacadeImpl.java
  src/main/java/com/example/surveyapp/domain/product/presentation/ProductController.java
  src/main/java/com/example/surveyapp/domain/product/presentation/dto/ProductStatusUpdateRequestDto.java
  src/main/java/com/example/surveyapp/domain/product/presentation/dto/ProductStatusUpdateResponseDto.java
  src/test/java/com/example/surveyapp/domain/product/application/ProductServiceTest.java
  src/test/java/com/example/surveyapp/domain/product/presentation/ProductControllerTest.java
Labels: feature

#304 Issues/298 Survey, SurveyAnswer Controller 테스트, 응답dto 날짜 형식 변경
  src/main/java/com/example/surveyapp/domain/surveyanswer/presentation/SurveyAnswerController.java
  src/main/java/com/example/surveyapp/global/config/JacksonConfig.java
  src/test/java/com/example/surveyapp/config/testbase/WebMvcTestBase.java
  src/test/java/com/example/surveyapp/domain/survey/presentation/OptionsControllerTest.java
  src/test/java/com/example/surveyapp/domain/survey/presentation/QuestionControllerTest.java
  src/test/java/com/example/surveyapp/domain/survey/presentation/SurveyControllerTest.java
  src/test/java/com/example/surveyapp/domain/surveyanswer/presentation/SurveyAnswerControllerTest.java
Labels: refactor, test

#344 Issues/294 ai, user controller test, api 문서화 추가
  src/docs/asciidoc/ai/ai.adoc
  src/docs/asciidoc/ai/ask-question.adoc
  src/docs/asciidoc/ai/index-text.adoc
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/user/get-base-data-info.adoc
  src/docs/asciidoc/user/get-base-datas.adoc
  src/docs/asciidoc/user/get-my-page.adoc
  src/docs/asciidoc/user/save-base-datas.adoc
  src/docs/asciidoc/user/update-my-page.adoc
  src/docs/asciidoc/user/user.adoc
  src/test/java/com/example/surveyapp/domain/ai/presentation/ChatControllerTest.java
  src/test/java/com/example/surveyapp/domain/survey/application/QuestionServiceTest.java
  src/test/java/com/example/surveyapp/domain/survey/presentation/QuestionControllerTest.java
  src/test/java/com/example/surveyapp/domain/survey/presentation/SurveyControllerTest.java
  src/test/java/com/example/surveyapp/domain/user/presentation/UserControllerTest.java
Labels: test

#378 Issues/377 컨트롤러 테스트 에러 해결
  src/test/java/com/example/surveyapp/config/testmockbeans/TestMockBeans.java
Labels: fix

#388 chore: 스케쥴러 사용을 위한 Config 설정
  src/main/java/com/example/surveyapp/global/config/SchedulingConfig.java
Labels: feature, refactor

#399 SurveyAnswerOutbox 구현 Issues/393
  src/main/java/com/example/surveyapp/domain/surveyanswer/application/SurveyAnswerOutboxScheduler.java
  src/main/java/com/example/surveyapp/domain/surveyanswer/application/SurveyAnswerService.java
  src/main/java/com/example/surveyapp/domain/surveyanswer/application/mapper/SurveyAnswerMapper.java
  src/main/java/com/example/surveyapp/domain/surveyanswer/domain/model/entity/AnserEnum.java
  src/main/java/com/example/surveyapp/domain/surveyanswer/domain/model/entity/SurveyAnswer.java
  src/main/java/com/example/surveyapp/domain/surveyanswer/domain/model/entity/SurveyAnswerOutbox.java
  src/main/java/com/example/surveyapp/domain/surveyanswer/domain/model/entity/SurveyOptionsAnswer.java
  src/main/java/com/example/surveyapp/domain/surveyanswer/domain/model/entity/SurveyTextAnswer.java
  src/main/java/com/example/surveyapp/domain/surveyanswer/domain/repository/SurveyAnswerOutboxRepository.java
  src/main/java/com/example/surveyapp/domain/surveyanswer/domain/repository/SurveyAnswerRepository.java
  src/main/java/com/example/surveyapp/domain/surveyanswer/domain/repository/SurveyOptionsAnswerRepository.java
  src/main/java/com/example/surveyapp/domain/surveyanswer/domain/repository/SurveyTextAnswerRepository.java
  src/main/java/com/example/surveyapp/domain/surveyanswer/domain/strategy/MultiChoiceAnswerStrategy.java
  src/main/java/com/example/surveyapp/domain/surveyanswer/domain/strategy/SingleChoiceAnswerStrategy.java
  src/main/java/com/example/surveyapp/domain/surveyanswer/domain/strategy/SubjectAnswerStrategy.java
  src/main/java/com/example/surveyapp/domain/surveyanswer/domain/strategy/SurveyQuestionStrategy.java
  src/main/java/com/example/surveyapp/domain/surveyanswer/exception/AnswerErrorCode.java
  src/main/java/com/example/surveyapp/domain/surveyanswer/infrastructure/SurveyAnswerJpaRepository.java
  src/main/java/com/example/surveyapp/domain/surveyanswer/infrastructure/SurveyAnswerOutboxJpaRepository.java
  src/main/java/com/example/surveyapp/domain/surveyanswer/infrastructure/SurveyAnswerOutboxRepositoryImpl.java
  src/main/java/com/example/surveyapp/domain/surveyanswer/infrastructure/SurveyAnswerRepositoryImpl.java
  src/main/java/com/example/surveyapp/domain/surveyanswer/infrastructure/SurveyOptionsAnswerJpaRepository.java
  src/main/java/com/example/surveyapp/domain/surveyanswer/infrastructure/SurveyOptionsAnswerRepositoryImpl.java
  src/main/java/com/example/surveyapp/domain/surveyanswer/infrastructure/SurveyTextAnswerJpaRepository.java
  src/main/java/com/example/surveyapp/domain/surveyanswer/infrastructure/SurveyTextAnswerRepositoryImpl.java
Labels: feature, refactor

#410 Issues/409 Outbox Fail Event 처리 로직 수정
  src/main/java/com/example/surveyapp/domain/order/domain/model/Order.java
  src/main/java/com/example/surveyapp/domain/order/domain/model/vo/OrderStatus.java
  src/main/java/com/example/surveyapp/domain/point/application/PointEarnRedeemService.java
  src/main/java/com/example/surveyapp/domain/point/application/PointOutboxScheduler.java
  src/main/java/com/example/surveyapp/domain/point/application/eventhandler/OrderPointEventHandler.java
  src/main/java/com/example/surveyapp/domain/point/application/eventhandler/PaymentPointEventHandler.java
  src/main/java/com/example/surveyapp/domain/point/application/eventhandler/SurveyPointEventHandler.java
  src/main/java/com/example/surveyapp/domain/survey/application/eventhandler/SurveyEventHandler.java
  src/main/java/com/example/surveyapp/domain/survey/domain/model/enums/SurveyStatus.java
Labels: fix

#445 Issues/444 RestDocs 수정
  src/docs/asciidoc/ai/index-text.adoc
  src/test/java/com/example/surveyapp/domain/admin/presentation/AdminControllerTest.java
  src/test/java/com/example/surveyapp/domain/ai/presentation/ChatControllerTest.java
  src/test/java/com/example/surveyapp/domain/order/presentation/OrderControllerTest.java
  src/test/java/com/example/surveyapp/domain/payment/presentation/PaymentControllerTest.java
  src/test/java/com/example/surveyapp/domain/point/presentation/PointControllerTest.java
  src/test/java/com/example/surveyapp/domain/product/presentation/ProductControllerTest.java
  src/test/java/com/example/surveyapp/domain/survey/presentation/OptionsControllerTest.java
  src/test/java/com/example/surveyapp/domain/survey/presentation/QuestionControllerTest.java
  src/test/java/com/example/surveyapp/domain/survey/presentation/SurveyControllerTest.java
  src/test/java/com/example/surveyapp/domain/surveyanswer/presentation/SurveyAnswerControllerTest.java
  src/test/java/com/example/surveyapp/domain/user/presentation/UserControllerTest.java
Labels: refactor, test

#457 Issues/456 README 수정
  README.md
  src/docs/assets/performance-testing/동시성/1.png
  src/docs/assets/performance-testing/동시성/10.png
  src/docs/assets/performance-testing/동시성/11.png
  src/docs/assets/performance-testing/동시성/12.png
  src/docs/assets/performance-testing/동시성/13.png
  src/docs/assets/performance-testing/동시성/14.png
  src/docs/assets/performance-testing/동시성/15.png
  src/docs/assets/performance-testing/동시성/2.png
  src/docs/assets/performance-testing/동시성/3.png
  src/docs/assets/performance-testing/동시성/4.png
  src/docs/assets/performance-testing/동시성/5.png
  src/docs/assets/performance-testing/동시성/6.png
  src/docs/assets/performance-testing/동시성/7.png
  src/docs/assets/performance-testing/동시성/8.png
  src/docs/assets/performance-testing/동시성/9.png
  src/docs/assets/performance-testing/캐시/1.png
  src/docs/assets/performance-testing/캐시/2.png
  src/docs/assets/performance-testing/캐시/3.png
  src/docs/assets/performance-testing/캐시/4.png
Labels: docs
